# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 18 Mar 2014 10:48:48 +0000
*               @ALL          0
*               @user         8
