<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Mon, 19 Jan 2015 03:02:18 -0500
 */

$conf['title'] = '@n1meFr3@k';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['updatecheck'] = 0;

// end auto-generated content
